package provider

import (
	"context"
	"fmt"

	"github.com/Fabianoshz/terraform-provider-homeassistant/internal/client"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

var _ resource.Resource = &FloorResource{}

type FloorResource struct {
	client *client.Client
}

func NewFloorResource() resource.Resource {
	return &FloorResource{}
}

type FloorResourceModel struct {
	ID      types.String `tfsdk:"id"`
	FloorID types.String `tfsdk:"floor_id"`
	Name    types.String `tfsdk:"name"`
	Level   types.Int64  `tfsdk:"level"`
	Icon    types.String `tfsdk:"icon"`
}

func (r *FloorResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_floor"
}

func (r *FloorResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages a Home Assistant floor.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"floor_id": schema.StringAttribute{
				Computed:    true,
				Description: "The floor ID generated by Home Assistant (slugified from the name).",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"name": schema.StringAttribute{
				Required:    true,
				Description: "Display name of the floor.",
			},
			"level": schema.Int64Attribute{
				Optional:    true,
				Computed:    true,
				Description: "Numeric level of the floor (e.g. 0 for ground, 1 for first floor).",
				PlanModifiers: []planmodifier.Int64{
					int64planmodifier.UseStateForUnknown(),
				},
			},
			"icon": schema.StringAttribute{
				Optional:    true,
				Description: "MDI icon for the floor (e.g. \"mdi:home-floor-1\").",
			},
		},
	}
}

func (r *FloorResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	c, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError("Unexpected provider data type", fmt.Sprintf("Expected *client.Client, got %T", req.ProviderData))
		return
	}
	r.client = c
}

func (r *FloorResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan FloorResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	floor, err := r.client.CreateFloor(ctx, plan.Name.ValueString(), int64PtrToIntPtr(plan.Level), valueOrNil(plan.Icon))
	if err != nil {
		resp.Diagnostics.AddError("Failed to create floor", err.Error())
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, floorToModel(floor))...)
}

func (r *FloorResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state FloorResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	floor, err := r.client.GetFloor(ctx, state.FloorID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Failed to read floor", err.Error())
		return
	}
	if floor == nil {
		resp.State.RemoveResource(ctx)
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, floorToModel(floor))...)
}

func (r *FloorResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan FloorResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	var state FloorResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	floor, err := r.client.UpdateFloor(ctx, state.FloorID.ValueString(), plan.Name.ValueString(), int64PtrToIntPtr(plan.Level), valueOrNil(plan.Icon))
	if err != nil {
		resp.Diagnostics.AddError("Failed to update floor", err.Error())
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, floorToModel(floor))...)
}

func (r *FloorResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state FloorResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	if err := r.client.DeleteFloor(ctx, state.FloorID.ValueString()); err != nil {
		resp.Diagnostics.AddError("Failed to delete floor", err.Error())
	}
}

func floorToModel(f *client.Floor) FloorResourceModel {
	m := FloorResourceModel{
		ID:      types.StringValue(f.FloorID),
		FloorID: types.StringValue(f.FloorID),
		Name:    types.StringValue(f.Name),
		Icon:    stringPtrValue(f.Icon),
		Level:   types.Int64Null(),
	}
	if f.Level != nil {
		m.Level = types.Int64Value(int64(*f.Level))
	}
	return m
}

func int64PtrToIntPtr(v types.Int64) *int {
	if v.IsNull() || v.IsUnknown() {
		return nil
	}
	i := int(v.ValueInt64())
	return &i
}
