package provider

import (
	"context"
	"fmt"

	"github.com/Fabianoshz/terraform-provider-homeassistant/internal/client"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

var _ resource.Resource = &LabelResource{}

type LabelResource struct {
	client *client.Client
}

func NewLabelResource() resource.Resource {
	return &LabelResource{}
}

type LabelResourceModel struct {
	ID          types.String `tfsdk:"id"`
	LabelID     types.String `tfsdk:"label_id"`
	Name        types.String `tfsdk:"name"`
	Color       types.String `tfsdk:"color"`
	Icon        types.String `tfsdk:"icon"`
	Description types.String `tfsdk:"description"`
}

func (r *LabelResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_label"
}

func (r *LabelResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages a Home Assistant label.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"label_id": schema.StringAttribute{
				Computed:    true,
				Description: "The label ID generated by Home Assistant (slugified from the name).",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"name": schema.StringAttribute{
				Required:    true,
				Description: "Display name of the label.",
			},
			"color": schema.StringAttribute{
				Optional:    true,
				Description: "Color of the label (e.g. \"primary\", \"red\", \"indigo\").",
			},
			"icon": schema.StringAttribute{
				Optional:    true,
				Description: "MDI icon for the label (e.g. \"mdi:tag\").",
			},
			"description": schema.StringAttribute{
				Optional:    true,
				Description: "Description of the label.",
			},
		},
	}
}

func (r *LabelResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	c, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError("Unexpected provider data type", fmt.Sprintf("Expected *client.Client, got %T", req.ProviderData))
		return
	}
	r.client = c
}

func (r *LabelResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan LabelResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	label, err := r.client.CreateLabel(ctx, plan.Name.ValueString(), valueOrNil(plan.Color), valueOrNil(plan.Icon), valueOrNil(plan.Description))
	if err != nil {
		resp.Diagnostics.AddError("Failed to create label", err.Error())
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, labelToModel(label))...)
}

func (r *LabelResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state LabelResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	label, err := r.client.GetLabel(ctx, state.LabelID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Failed to read label", err.Error())
		return
	}
	if label == nil {
		resp.State.RemoveResource(ctx)
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, labelToModel(label))...)
}

func (r *LabelResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan LabelResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	var state LabelResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	label, err := r.client.UpdateLabel(ctx, state.LabelID.ValueString(), plan.Name.ValueString(), valueOrNil(plan.Color), valueOrNil(plan.Icon), valueOrNil(plan.Description))
	if err != nil {
		resp.Diagnostics.AddError("Failed to update label", err.Error())
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, labelToModel(label))...)
}

func (r *LabelResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state LabelResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	if err := r.client.DeleteLabel(ctx, state.LabelID.ValueString()); err != nil {
		resp.Diagnostics.AddError("Failed to delete label", err.Error())
	}
}

func labelToModel(l *client.Label) LabelResourceModel {
	return LabelResourceModel{
		ID:          types.StringValue(l.LabelID),
		LabelID:     types.StringValue(l.LabelID),
		Name:        types.StringValue(l.Name),
		Color:       stringPtrValue(l.Color),
		Icon:        stringPtrValue(l.Icon),
		Description: stringPtrValue(l.Description),
	}
}
