package provider

import (
	"context"
	"fmt"

	"github.com/Fabianoshz/terraform-provider-home-assistant/internal/client"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

var _ resource.Resource = &AreaResource{}

type AreaResource struct {
	client *client.Client
}

func NewAreaResource() resource.Resource {
	return &AreaResource{}
}

type AreaResourceModel struct {
	ID     types.String `tfsdk:"id"`
	AreaID types.String `tfsdk:"area_id"`
	Name   types.String `tfsdk:"name"`
	Icon   types.String `tfsdk:"icon"`
}

func (r *AreaResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_area"
}

func (r *AreaResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages a Home Assistant area.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"area_id": schema.StringAttribute{
				Computed:    true,
				Description: "The area ID generated by Home Assistant (slugified from the name).",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"name": schema.StringAttribute{
				Required:    true,
				Description: "Display name of the area (e.g. \"Kitchen\").",
			},
			"icon": schema.StringAttribute{
				Optional:    true,
				Description: "MDI icon for the area (e.g. \"mdi:sofa\").",
			},
		},
	}
}

func (r *AreaResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	c, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError("Unexpected provider data type", fmt.Sprintf("Expected *client.Client, got %T", req.ProviderData))
		return
	}
	r.client = c
}

func (r *AreaResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan AreaResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	area, err := r.client.CreateArea(ctx, plan.Name.ValueString(), valueOrNil(plan.Icon))
	if err != nil {
		resp.Diagnostics.AddError("Failed to create area", err.Error())
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, areaToModel(area))...)
}

func (r *AreaResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state AreaResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	area, err := r.client.GetArea(ctx, state.AreaID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Failed to read area", err.Error())
		return
	}
	if area == nil {
		resp.State.RemoveResource(ctx)
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, areaToModel(area))...)
}

func (r *AreaResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan AreaResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	var state AreaResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	area, err := r.client.UpdateArea(ctx, state.AreaID.ValueString(), plan.Name.ValueString(), valueOrNil(plan.Icon))
	if err != nil {
		resp.Diagnostics.AddError("Failed to update area", err.Error())
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, areaToModel(area))...)
}

func (r *AreaResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state AreaResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	if err := r.client.DeleteArea(ctx, state.AreaID.ValueString()); err != nil {
		resp.Diagnostics.AddError("Failed to delete area", err.Error())
	}
}

func areaToModel(a *client.Area) AreaResourceModel {
	return AreaResourceModel{
		ID:     types.StringValue(a.AreaID),
		AreaID: types.StringValue(a.AreaID),
		Name:   types.StringValue(a.Name),
		Icon:   stringPtrValue(a.Icon),
	}
}
